<h1>Storelocator</h1>
<b>Display your locations on the map and make customers know where your offline shops are situated. </b>

<b>Here you can add your all store address and description with google map and many more. </b>

<h2>Store Locator </h2>
<p>
The Store Locator Magento extension is an amazing tool for merchants who have physical locations of retailers. The module gives you a help in adding store addresses to the website and navigating visitors to the required one.
</p>

<p>
You can create as many locations as you need - they will be displayed in a pleasant vertical presentation on a separate page. Just specify the address of your store and see how it will be automatically detected on the map. Let your customers easily find the page with addresses by adding store locations url to the top Magento links. Customers get to know all existed locations on the map and view the detailed information about them by clicking the store icon.
</p>