<?php
$prefix = Mage::getConfig()->getTablePrefix();
$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
$prefix = Mage::getConfig()->getTablePrefix();
$tblname=$prefix.'mksstorelocator'; 
$sql1 = $connection->query("select * from $tblname order by id limit 1" ); 
$row1 = $sql1->fetch();
$latitudex = $row1['lat'];
$longitudex = $row1['longt'];
$addressx = $row1['address'];
?>

<script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script> 
<script src="https://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script> 
<script type="text/javascript">

function map_xxx(x,y,z)
{
	var latitude = x; // parseFloat("26.850883100000000000");
	var longitude  = y; // parseFloat("75.824783600000040000");
        var address  = z; // "Rohini, New Delhi, Delhi, India";
	var latlngPos = new google.maps.LatLng(latitude,longitude);
        
        // Set up options for the Google map
        var myOptions = {
            zoom: 10,
            center: latlngPos,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            zoomControlOptions: true,
            zoomControlOptions: {
                style: google.maps.ZoomControlStyle.LARGE
            }
        };        
        // Define the map
        map = new google.maps.Map(document.getElementById("map"), myOptions);
        // Add the marker
        var marker = new google.maps.Marker({
            position: latlngPos,
            map: map,
            draggable: false,
            title: address
        }); 
               
};
</script>

<body onload="map_xxx('<?php  echo $latitudex ?>','<?php echo $longitudex; ?>','<?php echo $addressx; ?>');">
<?php 
$sql = $connection->query("select * from $tblname where status='0'" ); 
?> 
