<?php
$connection = Mage::getSingleton('core/resource')->getConnection('core_write'); 
$sql1 = $connection->query("select * from mksstorelocator order by id limit 1" ); 
$row1 = $sql1->fetch();
$latitudex = $row1['lat'];
$longitudex = $row1['longt'];
$addressx = $row1['address'];
?>

<script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script> 
<script src="https://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script> 
<script type="text/javascript">

function map_xxx(x,y,z)
{
	var latitude = x; // parseFloat("26.850883100000000000");
	var longitude  = y; // parseFloat("75.824783600000040000");
        var address  = z; // "Rohini, New Delhi, Delhi, India";
	var latlngPos = new google.maps.LatLng(latitude,longitude);
        
        // Set up options for the Google map
        var myOptions = {
            zoom: 10,
            center: latlngPos,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            zoomControlOptions: true,
            zoomControlOptions: {
                style: google.maps.ZoomControlStyle.LARGE
            }
        };        
        // Define the map
        map = new google.maps.Map(document.getElementById("map"), myOptions);
        // Add the marker
        var marker = new google.maps.Marker({
            position: latlngPos,
            map: map,
            draggable: false,
            title: address
        }); 
               
};
</script>

<body onload="map_xxx('<?php  echo $latitudex ?>','<?php echo $longitudex; ?>','<?php echo $addressx; ?>');">

<table id="map_xxx" style="width:900px; border:10px;">
<tr><td style="width:400px;">
<?php
$sql = $connection->query("select * from mksstorelocator" ); 
while($row = $sql->fetch())
{?>
<table id="store-table" class="store-table">
<tr>
<td rowspan="8" class="store-image">
<img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$row['image']; ?>" alt="Manvendra sharma" width="50">
</td>
</tr>
<tr>
<td>
<h3 class="store_name"  onclick="map_xxx('<?php echo $row['lat']; ?>','<?php echo $row['longt']; ?>','<?php echo $row['address']; ?>');"><?php echo $row['name']; ?></h3>
</td>
</tr>
<tr>
<td class="col-address"><?php echo $row['city']; ?></td>
</tr>
<tr>
<?php 
$add = $row['zipcode'].$row['address'];
?>
<td class="col-address"><?php echo $add; ?></td>
</tr>
<tr>
<td class="col-address"><?php echo $row['country_id']; ?> </td> 
 </tr>
 <tr>
<td>Website : <a href="<?php echo $row['store_url']; ?>" target="_blank"><?php echo $row['store_url']; ?></a></td>
</tr>
<tr>
<td> Phone :<?php echo $row['phone']; ?>   </td>
</tr>
<tr>
 <td>  Fax :<?php echo $row['fax']; ?></td>
 </tr>
</table>
<?php   }  ?>

</td>

<td style="width:500px;">
<div id="map" style="width:500px; height:500px;"></div>
</td></tr></table>
